### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by SinonCute** [StarchierOrb/InventoryKeeper#1]
[03:02:55] [Server thread/ERROR]: Could not pass event PlayerDeathEvent to InventoryKeeper v1.4.2
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
	at me.starchier.inventorykeeper.command.CommandExec.processRandom(CommandExec.java:155) ~[?:?]
	at me.starchier.inventorykeeper.command.CommandExec.runCommands(CommandExec.java:48) ~[?:?]
	at me.starchier.inventorykeeper.events.DeathHandler.onPlayerDeath(DeathHandler.java:214) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor102.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-780]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-780]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-780]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:624) ~[patched_1.16.5.jar:git-Paper-780]
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:876) ~[patched_1.16.5.jar:git-Paper-780]
	at net.minecraft.server.v1_16_R3.EntityPlayer.die(EntityPlayer.java:818) ~[patched_1.16.5.jar:git-Paper-780]
	at net.minecraft.server.v1_16_R3.EntityLiving.damageEntity(EntityLiving.java:1362) ~[patched_1.16.5.jar:git-Paper-780]
	at net.minecraft.server.v1_16_R3.EntityHuman.damageEntity(EntityHuman.java:870) ~[patched_1.16.5.jar:git-Paper-780]
	at net.minecraft.server.v1_16_R3.EntityPlayer.damageEntity(EntityPlayer.java:982) ~[patched_1.16.5.jar:git-Paper-780]
	at net.minecraft.server.v1_16_R3.EntityHuman.attack(EntityHuman.java:1196) ~[patched_1.16.5.jar:git-Paper-780]
	at net.minecraft.server.v1_16_R3.EntityPlayer.attack(EntityPlayer.java:2022) ~[patched_1.16.5.jar:git-Paper-780]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2413) ~[patched_1.16.5.jar:git-Paper-780]
	at net.minecraft.server.v1_16_R3.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:55) ~[patched_1.16.5.jar:git-Paper-780]
	at net.minecraft.server.v1_16_R3.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:12) ~[patched_1.16.5.jar:git-Paper-780]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-780]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-780]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-780]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-780]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-780]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1266) ~[patched_1.16.5.jar:git-Paper-780]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1259) ~[patched_1.16.5.jar:git-Paper-780]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.16.5.jar:git-Paper-780]
	at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1395) ~[patched_1.16.5.jar:git-Paper-780]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1130) ~[patched_1.16.5.jar:git-Paper-780]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-780]
	at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by StarchierOrb** [comment]
This problem may be caused by a config error.
Try to check your config in "run-random-commands" group.
