### ISSUE TITLE
Could not pass event PlayerDeathEvent to InventoryKeeper v2.0.1 when /gamerule world keepInventory true

### ISSUE THREAD

**Issue by l3unnyAnoF4** [StarchierOrb/InventoryKeeper#3]
```
[07:46:30 ERROR]: Could not pass event PlayerDeathEvent to InventoryKeeper v2.0.1
[07:46:30 ERROR]: Suspected Plugins:
[07:46:30 ERROR]:       InventoryKeeper{enabled,ver=2.0.1,path=plugins\InventoryKeeper-2.0.1.jar}
[07:46:30 ERROR]: Exception details below:
java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because the return value of "java.util.HashMap.get(Object)" is null
        at me.starchier.inventorykeeper.events.DeathHandler.forceKeepInventory(DeathHandler.java:308) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor104.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[ssspigot217009992202798189207.jar:SSSpigot2-1.17.1-20210812-6b7c58e]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[ssspigot217009992202798189207.jar:SSSpigot2-1.17.1-20210812-6b7c58e]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[ssspigot217009992202798189207.jar:SSSpigot2-1.17.1-20210812-6b7c58e]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:633) ~[ssspigot217009992202798189207.jar:SSSpigot2-1.17.1-20210812-6b7c58e]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:889) ~[ssspigot217009992202798189207.jar:SSSpigot2-1.17.1-20210812-6b7c58e]
        at net.minecraft.server.level.ServerPlayer.die(ServerPlayer.java:831) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1459) ~[?:?]
        at net.minecraft.world.entity.player.Player.hurt(Player.java:923) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.hurt(ServerPlayer.java:997) ~[?:?]
        at net.minecraft.world.level.Explosion.explode(Explosion.java:250) ~[ssspigot217009992202798189207.jar:SSSpigot2-1.17.1-20210812-6b7c58e]
        at net.minecraft.world.level.Level.explode(Level.java:1121) ~[?:?]
        at net.minecraft.server.level.ServerLevel.explode(ServerLevel.java:1675) ~[?:?]
        at net.minecraft.world.level.Level.explode(Level.java:1118) ~[?:?]
        at net.minecraft.server.TickServ$1.evaluate(TickServ.java:46) ~[ssspigot217009992202798189207.jar:SSSpigot2-1.17.1-20210812-6b7c58e]
        at org.bukkit.craftbukkit.v1_17_R1.util.Waitable.run(Waitable.java:24) ~[ssspigot217009992202798189207.jar:SSSpigot2-1.17.1-20210812-6b7c58e]
        at net.minecraft.server.TickServ.flush(TickServ.java:227) ~[ssspigot217009992202798189207.jar:SSSpigot2-1.17.1-20210812-6b7c58e]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1573) ~[ssspigot217009992202798189207.jar:SSSpigot2-1.17.1-20210812-6b7c58e]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1289) ~[ssspigot217009992202798189207.jar:SSSpigot2-1.17.1-20210812-6b7c58e]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[ssspigot217009992202798189207.jar:SSSpigot2-1.17.1-20210812-6b7c58e]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[07:46:30 INFO]: Player was blown up by Creeper
```

**Comment by l3unnyAnoF4** [comment]
```
[07:51:42 ERROR]: Could not pass event PlayerDeathEvent to InventoryKeeper v2.0.1
[07:51:42 ERROR]: Suspected Plugins:
[07:51:42 ERROR]:       InventoryKeeper{enabled,ver=2.0.1,path=plugins\InventoryKeeper-2.0.1.jar}
[07:51:42 ERROR]: Exception details below:
java.lang.NullPointerException: Cannot invoke "java.lang.Boolean.booleanValue()" because the return value of "java.util.HashMap.get(Object)" is null
        at me.starchier.inventorykeeper.events.DeathHandler.forceKeepInventory(DeathHandler.java:308) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor104.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[ssspigot217009992202798189207.jar:SSSpigot2-1.17.1-20210812-6b7c58e]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[ssspigot217009992202798189207.jar:SSSpigot2-1.17.1-20210812-6b7c58e]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[ssspigot217009992202798189207.jar:SSSpigot2-1.17.1-20210812-6b7c58e]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:633) ~[ssspigot217009992202798189207.jar:SSSpigot2-1.17.1-20210812-6b7c58e]
        at org.bukkit.craftbukkit.v1_17_R1.event.CraftEventFactory.callPlayerDeathEvent(CraftEventFactory.java:889) ~[ssspigot217009992202798189207.jar:SSSpigot2-1.17.1-20210812-6b7c58e]
        at net.minecraft.server.level.ServerPlayer.die(ServerPlayer.java:831) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.hurt(LivingEntity.java:1459) ~[?:?]
        at net.minecraft.world.entity.player.Player.hurt(Player.java:923) ~[?:?]
        at net.minecraft.server.level.ServerPlayer.hurt(ServerPlayer.java:997) ~[?:?]
        at net.minecraft.world.entity.Mob.doHurtTarget(Mob.java:1578) ~[?:?]
        at net.minecraft.world.entity.monster.Zombie.doHurtTarget(Zombie.java:362) ~[?:?]
        at net.minecraft.world.entity.ai.goal.MeleeAttackGoal.checkAndPerformAttack(MeleeAttackGoal.java:142) ~[?:?]
        at net.minecraft.world.entity.ai.goal.MeleeAttackGoal.tick(MeleeAttackGoal.java:134) ~[?:?]
        at net.minecraft.world.entity.ai.goal.ZombieAttackGoal.tick(ZombieAttackGoal.java:28) ~[?:?]
        at net.minecraft.world.entity.ai.goal.WrappedGoal.tick(WrappedGoal.java:53) ~[?:?]
        at net.minecraft.world.entity.ai.goal.GoalSelector.tick(GoalSelector.java:158) ~[?:?]
        at net.minecraft.world.entity.Mob.serverAiStep(Mob.java:854) ~[?:?]
        at net.minecraft.world.entity.LivingEntity.lambda$aiStep$7(LivingEntity.java:3174) ~[?:?]
        at net.minecraft.server.TickServ.lambda$entityPack$2(TickServ.java:99) ~[ssspigot217009992202798189207.jar:SSSpigot2-1.17.1-20210812-6b7c58e]
        at net.minecraft.server.TickServ.flush(TickServ.java:227) ~[ssspigot217009992202798189207.jar:SSSpigot2-1.17.1-20210812-6b7c58e]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1573) ~[ssspigot217009992202798189207.jar:SSSpigot2-1.17.1-20210812-6b7c58e]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1289) ~[ssspigot217009992202798189207.jar:SSSpigot2-1.17.1-20210812-6b7c58e]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[ssspigot217009992202798189207.jar:SSSpigot2-1.17.1-20210812-6b7c58e]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[07:51:42 INFO]: Player was slain by Zombie
```
